import { Inter } from "next/font/google";
import { dir } from 'i18next'
import { languages, fallbackLng } from '../../lib/i18n/locales/setting'
import "./globals.css";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng} dir={dir(lng || fallbackLng)}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}